// export const STUDENT_INFO = {
// 	REQ: 'GET_STUDENT_INFO',
// 	RES: 'RES_STUDENT_INFO',
// 	FAIL: 'FAIL_STUDENT_INFO',
// 	CLEAR: 'CLEAR_STUDENT_INFO'
// };

export const ACADEMIC_YEAR_ACTIONS = {
	REQ: 'GET_ACADEMIC_YEAR_LIST',
	RES: 'RES_ACADEMIC_YEAR_LIST',
	FAIL: 'FAIL_ACADEMIC_YEAR_LIST',
	SET_ACTIVE_ACADEMIC_YEAR: 'SET_ACTIVE_ACADEMIC_YEAR'
};
export const GROUP_ACTIONS = {
	REQ: 'GET_GROUP_ACTIONS ',
	RES: 'RES_GROUP_ACTIONS ',
	FAIL: 'FAIL_GROUP_ACTIONS ',
	SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP '
};

// export const BRANCH_LIST_ACTIONS = {
// 	REQ: 'GET_BRANCH_LIST',
// 	RES: 'RES_BRANCH_LIST',
// 	FAIL: 'FAIL_BRANCH_LIST',
// 	SET_ACTIVE_BRANCH: 'SET_ACTIVE_BRANCH'
// };

// export const CLASS_LIST_ACTIONS = {
// 	REQ: 'GET_CLASS_LIST',
// 	RES: 'RES_CLASS_LIST',
// 	FAIL: 'FAIL_CLASS_LIST',
// 	SET_ACTIVE_CLASS: 'SET_ACTIVE_CLASS'
// };

// export const SECTION_LIST_ACTIONS = {
// 	REQ: 'GET_SECTION_LIST',
// 	RES: 'RES_SECTION_LIST',
// 	FAIL: 'FAIL_SECTION_LIST',
// 	SET_ACTIVE_SECTION: 'SET_ACTIVE_SECTION'
// };

// export const STUDENT_MASTER_LIST = {
// 	REQ: 'GET_STUDENT_MASTER_LIST',
// 	RES: 'RES_STUDENT_MASTER_LIST',
// 	FAIL: 'FAIL_STUDENT_MASTER_LIST'
// };
