const temp = [ '33.5', '40.8', '32.1', '45.0', '28.0', 'Welcome', 'Nice', 'Good', 'brew', 'food', 'flower', 'voice' ],
	gram = [ '435', '324', '536', '640', '654' ],
	others = [ '43', '25', '36', '48', '65' ];
export const labReport = [
	{
		refference_name: 'error_balance_mixing',
		name: 'Error in Balance (Mixing) in Grams',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: 'Zero Error',
		units: 'Grams',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'syrup_temp',
		name: 'Syrup Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'fat_temp',
		name: 'Fat Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'broken_biscuit',
		name: 'Broken Biscuit Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'ground_sugar',
		name: 'Ground Sugar Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'process_water',
		name: 'Process Water Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'dough_temp',
		name: 'Dough Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'weight_of_raw_biscuit',
		name: 'Wt. of Raw Biscuit in Grams',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: 'Zero Error',
		units: 'Grams',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'prpm_rotary',
		name: 'RPM of Rotary Moulder',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'baking_time',
		name: 'Baking Time in Min-Sec',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'error_balance_rotary',
		name: 'Error in Balance (Rotary) in Grams',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: 'Zero Error',
		units: 'Grams',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'color_impression_biscuit',
		name: 'Color and Impression of Biscuit',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'error_balance_ovenend',
		name: 'Error in Balance (Oven End) in Grams',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: 'Zero Error',
		units: 'Grams',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'biscuit_temp',
		name: 'Biscuit Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'stamping',
		name: 'Stamping of Complaint Slips',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'packing',
		name: 'Packing Quality',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'code_family_pack_machine',
		name: 'Running Code on Family Pack Machine',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'polybag_dimension',
		name: 'Polybag Dimension',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'cbox_dimension',
		name: 'C-Box Dimension',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'cbox_taping',
		name: 'C-Box Taping Quality',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'record_working',
		name: 'Record of Working',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'control_charts',
		name: 'Use of Control Charts',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '',
		units: '',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'packing_hall',
		name: 'Packing Hall Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	},
	{
		refference_name: 'mixing_hall',
		name: 'Mixing Hall Temp. in °C',
		category: '',
		contentType: '',
		group: '',
		loaction: '',
		standardValue: '35',
		units: 'Temp °C',
		remarks: '',
		value1: temp[Math.floor(Math.random() * temp.length)],
		value2: temp[Math.floor(Math.random() * temp.length)],
		value3: temp[Math.floor(Math.random() * temp.length)],
		value4: temp[Math.floor(Math.random() * temp.length)]
	}
];

export const sample = {
	Approvals: [
		{
			approverCode: 'inCharge',
			Name: 'Shift QA In-charge',
			isApproved: true, //{true/false}
			comments: '',
			approvedTime: '' // time of approval submited
		},
		{
			approverCode: 'parlemanager',
			Name: 'Parle Manager',
			isApproved: true, //{true/false}
			comments: '',
			approvedTime: '' // time of approval submited
		},
		{
			approverCode: 'prodManager',
			Name: 'Prod.Manager',
			isApproved: true, //{true/false}
			comments: '',
			approvedTime: '' // time of approval submited
		},
		{
			approverCode: 'director',
			Name: 'Director',
			isApproved: true, //{true/false}
			comments: '',
			approvedTime: '' // time of approval submited
		}
	],
	id: 3007,
	date: '17/03/2022',
	name: 'Daily Laboratory Report',
	createdtime: '',
	Records: [
		{
			refference_name: 'error_balance_mixing',
			name: 'Error in Balance (Mixing) in Grams',
			standardValue: 'Zero Error',
			refference_name_remarks: '',
			value: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'syrup_temp',
			name: 'Syrup Temp. in °C',
			standardValue: '35',
			refference_name_remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'fat_temp',
			name: 'Fat Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'broken_biscuit',
			name: 'Broken Biscuit Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'ground_sugar',
			name: 'Ground Sugar Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'process_water',
			name: 'Process Water Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'dough_temp',
			name: 'Dough Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'weight_of_raw_biscuit',
			name: 'Wt. of Raw Biscuit in Grams',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: 'Zero Error',
			units: 'Grams',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'prpm_rotary',
			name: 'RPM of Rotary Moulder',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'baking_time',
			name: 'Baking Time in Min-Sec',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'error_balance_rotary',
			name: 'Error in Balance (Rotary) in Grams',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: 'Zero Error',
			units: 'Grams',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'color_impression_biscuit',
			name: 'Color and Impression of Biscuit',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'error_balance_ovenend',
			name: 'Error in Balance (Oven End) in Grams',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: 'Zero Error',
			units: 'Grams',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'biscuit_temp',
			name: 'Biscuit Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'stamping',
			name: 'Stamping of Complaint Slips',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'packing',
			name: 'Packing Quality',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'code_family_pack_machine',
			name: 'Running Code on Family Pack Machine',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'polybag_dimension',
			name: 'Polybag Dimension',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'cbox_dimension',
			name: 'C-Box Dimension',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'cbox_taping',
			name: 'C-Box Taping Quality',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'record_working',
			name: 'Record of Working',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'control_charts',
			name: 'Use of Control Charts',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '',
			units: '',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'packing_hall',
			name: 'Packing Hall Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		},
		{
			refference_name: 'mixing_hall',
			name: 'Mixing Hall Temp. in °C',
			category: '',
			contentType: '',
			group: '',
			loaction: '',
			standardValue: '35',
			units: 'Temp °C',
			remarks: '',
			value1: temp[Math.floor(Math.random() * temp.length)],
			value2: temp[Math.floor(Math.random() * temp.length)],
			value3: temp[Math.floor(Math.random() * temp.length)],
			value4: temp[Math.floor(Math.random() * temp.length)]
		}
	]
};
